# Generated by Django 4.2.6 on 2023-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_remove_employee_company_delete_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='citizenship_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
