# Generated by Django 4.2.6 on 2023-10-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_city'),
        ('api', '0004_signup'),
    ]

    operations = [
    ]
