# Generated by Django 4.2.6 on 2023-10-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_confirmation_alter_signup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='DOB',
            field=models.CharField(default='01/01/2000', max_length=25),
        ),
    ]
