# Generated by Django 4.2.6 on 2023-10-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_confirmation_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('therapist_name', models.CharField(max_length=30)),
                ('date_of_consultation', models.CharField(max_length=20)),
                ('description_by_therapist', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
