# Generated by Django 4.2.6 on 2023-10-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_consultation_details_alter_confirmation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='signup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.signup'),
        ),
    ]
