# Generated by Django 4.2.6 on 2023-10-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_booking_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='referal_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
