# Generated by Django 4.2.6 on 2023-10-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_booking_referal_id_alter_signup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='therapist_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
